---
title: "Intermediate Micro Theory II"
subtitle: ""
author: "Hans Martinez"
institute: "Western University"
date: last-modified
date-format: long
format:
  revealjs: 
    slide-number: true
    # chalkboard: 
    #   buttons: false
    preview-links: true
    incremental: true
    theme: [simple, theme.scss ]
    width: 1260
    height: 700
    embed-resources: true
    navigation-mode: linear
    # revealjs-plugins:
    #   - fullscreen
    # include-in-header: packages.tex
    # css: [style.css, xaringan-themer.css]
    # logo: images/quarto.png
    # footer: <https://quarto.org>
# resources:
#   - Paper/WP-LCFI.pdf
# bibliography: biblio/lcfi.bib

---
## Economics

- Science that deals with the allocation of scarce resources to satisfy unlimited competing uses (human wants).

    - Human wants: goods and services, including food, clothing, shelter, etc.

    - Resources are *scarce*

    - Science of constrained choices

## Economics and the Social Sciences

- Economics and other Social Sciences overlap in studying human behavior (choices). 

    - Example: fertility behavior is considered part of sociology, anthropology, history, etc.

- Its **approach** distinguishes Economics from other Social Sciences

## Economic Approach

1. Maximizing behavior: Utility or profit function of the household, firm, union, or government

1. Market equilibrium: With varying degrees of efficiency, markets coordinate the actions of agents so that their behavior becomes mutually consistent (Prices)

1. Stable preferences: Preferences do not change over time and are not different between different types of individuals (wealth, nationality, culture)

## Wide Range

> The economic approach is not restricted to material goods and wants, not even to the market sector. Prices, be the money prices of the market sector or the "shadow" imputed prices of the nonmarket sector, measure the opportunity cost of using scarce resources (Becker, G., 1976, *The Economic Approach to Human Behavior*)

- fertility, education, crime, marriage, etc. 

## Microeconomics

- Economics is broadly divided into macro and microeconomics

- Microeconomics studies the economic behavior of individual decision-makers: consumers, workers, firms, governments


## Microeconomic Modeling

- *An economic model is a simplified description of reality designed to yield hypotheses [predictions] about economic behavior that can be tested*. [(Ouliaris, 2011)](https://www.imf.org/external/pubs/ft/fandd/2011/06/basics.htm)

- *A model is supposed to reveal the essence of what's going on*. (Varian, H., 2016)

- *All models are wrong, but some are useful* (Box, G., 1976)

## What Makes a Good Economic Model?

- The scientific method requires that every model yield precise and verifiable implications about the economic phenomena it is trying to explain

- Formal evaluation involves testing the model’s key implications and assessing its ability to reproduce stylized facts

- Economists use many tools to test their models, including case studies, lab-based experimental studies, and statistics

## Economic Models

- Agents (firms)
- Agents make choices to advance their objectives (firms maximize their profits)
- The choices have to satisfy various constraints so there's something that adjusts to make all these choices consistent (firms adjust their output to avoid losing money, P=MC)

## Economic Models

- Variables taken as given that do not need to be explained by the model are called **exogenous** variables.

- Variables determined by the model when the exogenous variables come into play are called **endogenous** variables.

## Example

Perfect competition

$$
\begin{align}
\max_{Q} \pi(Q)&=PQ-C(Q) \\
\text{s.t. } Q&\ge0
\end{align}
$$ {#eq-perf-comp}


## Example

- Agents: 

- Choices: 

- Constraints: 

- Exogenous variables: 

- Endogenous variables: 

## Example

- Agents: Firms

- Choices: Quantities

- Constraints: Positive quantities, producing more increases profits but it is costlier

- Exogenous variables: Prices, profit function, total cost function

- Endogenous variables: Quantities

## Analytical Tools

1. Constrained optimization

1. Equilibrium analysis

1. Comparative statics

## Constrained Optimization

- A decision maker optimizes its choice by maximizing (or minimizing) its **objective function**, taking into account the **constraints** on the choice

- The solution to a constraint optimization problem depends on the **marginal impact** of the decision variables on the value of the objective function

- Marginal value measures how a *dependent* variable changes as a result of one unit change of an *independent* variable

## Equilibrium Analysis

- Analysis of a system in a state that will continue indefinitely as long as the exogenous factors remain unchanged

## Comparative Statics

- Comparative statics analysis is used to examine how a change in an exogenous variable will affect the level of an endogenous variable in an economic model

- Comparative statics analysis can be applied to constrained optimization problems or equilibrium analyses

## Example

Perfect Competition

$$
P = \frac{dC}{dQ}
$$

- To solve @eq-perf-comp, firms select quantities such that prices are equal to their marginal cost



