---
title: "Note 4"
format:
    pdf:
        documentclass: article
        colorlinks: true
        # include-in-header: packages.tex
        keep-tex: true
        # resource-path: 
        #     - "Simulations/Products"
        # latex-output-dir: Output
number-sections: true
author: Hans Martinez
date: today
bibliography: biblio.bib
---
## Bundling: A Framework with Discrete Choices[^taken]

[^taken]: Adapted from @Armstrong2016 p. 596-598.

Consider a situation in which a monopolist supplies two products, labeled 1 and 2, and a consumer buys either zero or one unit of each product (and maybe a unit of each). A consumer’s preferences are described by the taste parameters $(v_1 , v_2 , v_b )$. She is willing to pay $v_i$ for product $i = 1, 2$ on its own and to pay $v_b$ for the bundle of both products. Assume the consumer’s valuations are additive $v_b = v_1 + v_2$.[^valuations] $p_1$ is the price for product 1 on its own, $p_2$ is the price for product 2 on its own, and $p_b$ is the price for the bundle of both products.

[^valuations]: Two products may also be partial substitutes if $v_b < v_1 + v_2$ or partial complements if $v_b >v_1+v_2$. The great majority of articles written on bundling as a form of price discrimination assume valuations are additive, as much for tractability as for realism.

A consumer chooses the option that leaves her with the highest net surplus. For example, with no bundling, she will buy product $i = 1,2$ whenever $v_i−p_i \ge 0$. In the case of bundling, the consumer will buy the bundle if $v_b-p_b\ge0$.

Lastly, in the case of mixed bundling, the consumer will buy both items whenever $v_b-p_b\ge \max{\{v_1−p_1,v_2−p_2,0\}}$, she will buy product $i = 1,2$ on its own whenever $v_i−p_i \ge \max\{v_b − p_b, v_j − p_j, 0\}$, and otherwise she will buy neither product.

As a function of the price schedule $(p_1,p_2,p_b)$, denote by $Q_i$ the number of consumers who buy only product $i=1,2$, and $Q_b$ the number of consumers who buy the bundle. 

If the marginal cost of supplying product $i=1,2$ is $c_i$, the seller's profit-maximizing problem is

$$
\max_{\{p_1,p_2,p_b\}} \pi=(p_1-c_1)Q_1 + (p_2-c_2)Q_2 + (p_b-c_1-c_2)Q_b
$$

When valuations are additive, the revenue from selling two products using bundling (nonlinear) pricing is greater than the sum of selling the two products separately with linear prices. Negative correlation in additive valuations makes it more likely that bundling is profitable. Negative correlation puts less weight on the *northeast* part of the graph.

### Examples



## References {-}

::: {#refs}
:::